data_config:
  train_file: index.txt
  val_file: eval_index.txt
  test_file: eval_index.txt
  num_proc: 1

combine: True
freezeV: True
max_input_length: 16384
max_output_length: 384
swanlab: "local"  # set to local if don`t use cloud

training_args:
  # see `transformers.Seq2SeqTrainingArguments`
  gradient_checkpointing: true
  optim: "adamw_torch_8bit"
  bf16: true
  output_dir: ./output
  max_steps: 12
  # needed to be fit for the dataset
  learning_rate: 5e-4
  # settings for data loading
  per_device_train_batch_size: 1
  dataloader_num_workers: 1
  remove_unused_columns: false
  # settings for saving checkpoints
  save_strategy: steps
  save_steps: 6
  # settings for logging
  log_level: info
  logging_strategy: steps
  logging_steps: 1
  run_name: "glm4-lora-finetune"
  # settings for evaluation
  per_device_eval_batch_size: 1
  eval_strategy: steps
  eval_steps: 3
  # settings for optimizer
  # adam_epsilon: 1e-6
  # uncomment the following line to detect nan or inf values
  # debug: underflow_overflow
  predict_with_generate: true
  # see `transformers.GenerationConfig`
  generation_config:
    max_new_tokens: 384
  # set your absolute deepspeed path here
  # deepspeed: configs/ds_zero_3.json
  # deepspeed: configs/ds_zero_2.json

peft_config:
  peft_type: LORA
  task_type: CAUSAL_LM
  r: 8
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules: ["q_proj", "k_proj", "v_proj"]
